remote_theme: pmarsceill/just-the-docs
logo: "https://github.com/GuatemalaPortal/guatemalaportal.github.io/blob/main/static/LogoPortalFotos.jpg?raw=true"
title: Portal de Biodiversidad de Guatemala
description: Documentación para el Portal de Biodiversidad de Guatemala

